services:
  postgres:
    image: 'postgres:alpine'
    environment:
      - 'POSTGRES_DB=postgres'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=abobauser'
    ports:
      - '5432'
#  redis:
#    image: 'redis:latest'
#    ports:
#      - '6379'