services:
  postgres:
    image: "postgres:alpine"
    environment:
      - "POSTGRES_DB=postgres"
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_USER=abobauser"
    ports:
      - '5432'
  minio:
    image: quay.io/minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: "ROOTNAME"
      MINIO_ROOT_PASSWORD: "ROOTPASS"
    volumes:
      - ~/data/minio:/data
    command: server /data --console-address ":9001"

#  redis:
#    image: 'redis:latest'
#    ports:
#      - '6379'